[package]
name = "rust_os"
version = "0.1.0"
edition = "2018"

[dependencies]

// Disable stack unwinding (hopefully we define it later right?)
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"